// <auto-generated />
using System;
using DiaperScout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiaperScout.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiaperScoutDbContext))]
    [Migration("20260830104332_InitialDataFoundation")]
    partial class InitialDataFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diaperscout")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiaperScout.Domain.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("backpacks", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.DiscoveryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeGapId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultingObservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("KnowledgeGapId");

                    b.HasIndex("ResultingObservationId");

                    b.HasIndex("State");

                    b.ToTable("discovery_tasks", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.EditorialDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModeratorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorUserId");

                    b.HasIndex("ObservationId", "DecidedAtUtc");

                    b.ToTable("editorial_decisions", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("ObservationId", "SubmittedAtUtc");

                    b.ToTable("evidence_items", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.ExplorerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("explorer_profiles", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.KnowledgeGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("knowledge_gaps", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("RetailerId", "Postcode", "Name")
                        .IsUnique();

                    b.ToTable("locations", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("manufacturers", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateProductName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Narrative")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PriceAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PriceCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId", "CreatedAtUtc");

                    b.HasIndex("LocationId", "ObservedAtUtc");

                    b.HasIndex("ProductId", "ObservedAtUtc");

                    b.ToTable("observations", "diaperscout", t =>
                        {
                            t.HasCheckConstraint("CK_observations_subject", "\"ProductId\" IS NOT NULL OR \"CandidateProductName\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DiaperScout.Domain.PackType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CaseQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("PackagingNotes")
                        .HasColumnType("text");

                    b.Property<int>("PackagingType")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityPerPack")
                        .HasColumnType("integer");

                    b.Property<Guid>("SizeVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SizeVariantId", "QuantityPerPack", "PackagingType")
                        .IsUnique();

                    b.ToTable("pack_types", "diaperscout", t =>
                        {
                            t.HasCheckConstraint("CK_pack_types_quantity", "\"QuantityPerPack\" > 0");
                        });
                });

            modelBuilder.Entity("DiaperScout.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OfficialWebsiteUrl")
                        .HasColumnType("text");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ManufacturerId", "Name");

                    b.ToTable("products", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PackTypeId");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("product_identifiers", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BackingType")
                        .HasColumnType("integer");

                    b.Property<string>("ConstructionNotes")
                        .HasColumnType("text");

                    b.Property<int?>("FastenerCount")
                        .HasColumnType("integer");

                    b.Property<int>("FastenerType")
                        .HasColumnType("integer");

                    b.Property<int>("Fragrance")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasElasticWaistbandFront")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasElasticWaistbandRear")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasInnerLeakGuards")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasStandingLeakGuards")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasWetnessIndicator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsChlorineFree")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLatexFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColour")
                        .HasColumnType("text");

                    b.Property<string>("PrintDesign")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("WaistbandStyle")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("product_variants", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Retailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("retailers", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("BackpackId", "LocationId")
                        .IsUnique();

                    b.ToTable("saved_locations", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BackpackId", "ProductId")
                        .IsUnique();

                    b.ToTable("saved_products", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.SizeVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CapacityMl")
                        .HasColumnType("integer");

                    b.Property<int?>("HipMaximumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("HipMinimumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<string>("ManufacturerSize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WaistMaximumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WaistMinimumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("integer");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId", "ManufacturerSize")
                        .IsUnique();

                    b.ToTable("size_variants", "diaperscout", t =>
                        {
                            t.HasCheckConstraint("CK_size_variants_waist_range", "\"WaistMinimumCm\" IS NULL OR \"WaistMaximumCm\" IS NULL OR \"WaistMinimumCm\" <= \"WaistMaximumCm\"");
                        });
                });

            modelBuilder.Entity("DiaperScout.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("users", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Backpack", b =>
                {
                    b.HasOne("DiaperScout.Domain.ExplorerProfile", null)
                        .WithOne("Backpack")
                        .HasForeignKey("DiaperScout.Domain.Backpack", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Brand", b =>
                {
                    b.HasOne("DiaperScout.Domain.Manufacturer", null)
                        .WithMany("Brands")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.DiscoveryTask", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.KnowledgeGap", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeGapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Observation", null)
                        .WithMany()
                        .HasForeignKey("ResultingObservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.EditorialDecision", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ModeratorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.EvidenceItem", b =>
                {
                    b.HasOne("DiaperScout.Domain.Observation", null)
                        .WithMany("Evidence")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.ExplorerProfile", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithOne("ExplorerProfile")
                        .HasForeignKey("DiaperScout.Domain.ExplorerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.KnowledgeGap", b =>
                {
                    b.HasOne("DiaperScout.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.Location", b =>
                {
                    b.HasOne("DiaperScout.Domain.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Observation", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.PackType", b =>
                {
                    b.HasOne("DiaperScout.Domain.SizeVariant", null)
                        .WithMany("PackTypes")
                        .HasForeignKey("SizeVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Product", b =>
                {
                    b.HasOne("DiaperScout.Domain.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductIdentifier", b =>
                {
                    b.HasOne("DiaperScout.Domain.PackType", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("PackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductVariant", b =>
                {
                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedLocation", b =>
                {
                    b.HasOne("DiaperScout.Domain.Backpack", null)
                        .WithMany("SavedLocations")
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedProduct", b =>
                {
                    b.HasOne("DiaperScout.Domain.Backpack", null)
                        .WithMany("SavedProducts")
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.SizeVariant", b =>
                {
                    b.HasOne("DiaperScout.Domain.ProductVariant", null)
                        .WithMany("Sizes")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Backpack", b =>
                {
                    b.Navigation("SavedLocations");

                    b.Navigation("SavedProducts");
                });

            modelBuilder.Entity("DiaperScout.Domain.ExplorerProfile", b =>
                {
                    b.Navigation("Backpack");
                });

            modelBuilder.Entity("DiaperScout.Domain.Manufacturer", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("DiaperScout.Domain.Observation", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("DiaperScout.Domain.PackType", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("DiaperScout.Domain.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductVariant", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("DiaperScout.Domain.SizeVariant", b =>
                {
                    b.Navigation("PackTypes");
                });

            modelBuilder.Entity("DiaperScout.Domain.User", b =>
                {
                    b.Navigation("ExplorerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
