// <auto-generated />
using System;
using DiaperScout.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiaperScout.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiaperScoutDbContext))]
    [Migration("20260923100322_RetailerProductMonitoring")]
    partial class RetailerProductMonitoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("diaperscout")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiaperScout.Domain.Backpack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("backpacks", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActingUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("AffectedCanonicalIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EditorialRationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReferencesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActingUserId");

                    b.HasIndex("ProductId", "OccurredAtUtc");

                    b.ToTable("catalogue_audit_records", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentitySourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProposedBrandName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProposedDescriptionVisibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProposedGtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("ProposedManufacturerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedOfficialWebsiteUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProposedPackagingType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProposedProductFamily")
                        .HasColumnType("text");

                    b.Property<string>("ProposedProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("ProposedProductStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedProductType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProposedSku")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProposedVariantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PublishedProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SharedConstructionNotes")
                        .HasColumnType("text");

                    b.Property<string>("SharedDesignedFor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SharedFastenerCount")
                        .HasColumnType("integer");

                    b.Property<string>("SharedFragrance")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("SharedLatexFree")
                        .HasColumnType("boolean");

                    b.Property<string>("SharedPrimaryColour")
                        .HasColumnType("text");

                    b.Property<string>("SharedPrintDesign")
                        .HasColumnType("text");

                    b.Property<bool?>("SharedStandingLeakGuards")
                        .HasColumnType("boolean");

                    b.Property<string>("SharedWaistbandStyle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("SharedWetnessIndicator")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PublishedProductId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("catalogue_submissions", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionEditorialDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModeratorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorUserId");

                    b.HasIndex("SubmissionId", "DecidedAtUtc");

                    b.ToTable("catalogue_submission_editorial_decisions", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermissionEvidence")
                        .HasColumnType("text");

                    b.Property<string>("PermissionStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceNotes")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_catalogue_submission_images_ProductId_IsPrimary")
                        .HasFilter("\"ProductId\" IS NOT NULL AND \"IsPrimary\" = TRUE");

                    b.HasIndex("ProductId", "Role")
                        .IsUnique()
                        .HasFilter("\"ProductId\" IS NOT NULL AND \"Role\" <> 'Other'");

                    b.HasIndex("SubmissionId", "Role")
                        .IsUnique()
                        .HasFilter("\"Role\" <> 'Other'");

                    b.ToTable("catalogue_submission_images", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionRetailAffiliate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeepLinkMechanism")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Network")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RetailDestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("TrackingConfiguration")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RetailDestinationId", "LastVerifiedAtUtc");

                    b.HasIndex("SubmissionId", "RetailDestinationId")
                        .IsUnique();

                    b.ToTable("catalogue_submission_retail_affiliates", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionRetailDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RetailerId");

                    b.HasIndex("SubmissionId", "RetailerId");

                    b.ToTable("catalogue_submission_retail_destinations", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionSizeVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsorbencyBasisMethod")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AbsorbencySource")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FitMeasurementBasis")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<int?>("HipMaximumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("HipMinimumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<int?>("ManufacturerPackQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ManufacturerSize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ManufacturerStatedAbsorbencyMl")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WaistMaximumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WaistMinimumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("integer");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VariantId");

                    b.HasIndex("VariantId", "ManufacturerSize")
                        .IsUnique();

                    b.ToTable("catalogue_submission_size_variants", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasFilter("\"Name\" IS NULL");

                    b.HasIndex("SubmissionId", "Name")
                        .IsUnique();

                    b.ToTable("catalogue_submission_variants", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVariantOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackingType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ConstructionNotes")
                        .HasColumnType("text");

                    b.Property<string>("DesignedFor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FastenerCount")
                        .HasColumnType("integer");

                    b.Property<string>("FastenerType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Fragrance")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("HasStandingLeakGuards")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasWetnessIndicator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLatexFree")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryColour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrintDesign")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaistbandStyle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("VariantId")
                        .IsUnique();

                    b.ToTable("catalogue_submission_variant_overrides", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PermissionTerms")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("SubmissionId", "Area", "VerifiedAtUtc");

                    b.ToTable("catalogue_submission_verifications", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.ToTable("countries", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.DiscoveryTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeGapId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultingObservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("KnowledgeGapId");

                    b.HasIndex("ResultingObservationId");

                    b.HasIndex("State");

                    b.ToTable("discovery_tasks", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.EditorialDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModeratorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorUserId");

                    b.HasIndex("ObservationId", "DecidedAtUtc");

                    b.ToTable("editorial_decisions", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("ObservationId", "SubmittedAtUtc");

                    b.ToTable("evidence_items", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.ExplorerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("explorer_profiles", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.KnowledgeGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("knowledge_gaps", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("RetailerId", "Postcode", "Name")
                        .IsUnique();

                    b.ToTable("locations", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("manufacturers", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateProductName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Narrative")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PriceAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PriceCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId", "CreatedAtUtc");

                    b.HasIndex("LocationId", "ObservedAtUtc");

                    b.HasIndex("ProductId", "ObservedAtUtc");

                    b.ToTable("observations", "diaperscout", t =>
                        {
                            t.HasCheckConstraint("CK_observations_subject", "\"ProductId\" IS NOT NULL OR \"CandidateProductName\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DiaperScout.Domain.PackType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CaseQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("PackagingNotes")
                        .HasColumnType("text");

                    b.Property<int>("PackagingType")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityPerPack")
                        .HasColumnType("integer");

                    b.Property<Guid>("SizeVariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SizeVariantId", "QuantityPerPack", "PackagingType")
                        .IsUnique();

                    b.ToTable("pack_types", "diaperscout", t =>
                        {
                            t.HasCheckConstraint("CK_pack_types_quantity", "\"QuantityPerPack\" > 0");
                        });
                });

            modelBuilder.Entity("DiaperScout.Domain.PrivilegedRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL");

                    b.ToTable("privileged_role_assignments", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.PrivilegedRoleAssignmentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActingUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActingUserId");

                    b.HasIndex("SubjectUserId", "OccurredAtUtc");

                    b.ToTable("privileged_role_assignment_audits", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVisibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OfficialWebsiteUrl")
                        .HasColumnType("text");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ManufacturerId", "Name");

                    b.ToTable("products", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PackTypeId");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("product_identifiers", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackingType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ConstructionNotes")
                        .HasColumnType("text");

                    b.Property<string>("DesignedFor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FastenerCount")
                        .HasColumnType("integer");

                    b.Property<string>("FastenerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Fragrance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("HasStandingLeakGuards")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasWetnessIndicator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLatexFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryColour")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrintDesign")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaistbandStyle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique();

                    b.ToTable("product_variants", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Retailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentitySourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("IdentityVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("retailers", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerAffiliateProgramme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApplicationRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("CookieDurationDays")
                        .HasColumnType("integer");

                    b.Property<bool?>("DeepLinksAllowed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("PreferredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProgrammeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProgrammeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ProgrammeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ReferralTerms")
                        .HasColumnType("text");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RetailerId", "IsPreferred");

                    b.HasIndex("RetailerId", "Network", "ProgrammeId")
                        .IsUnique();

                    b.ToTable("retailer_affiliate_programmes", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerIdentityVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DomainMatches")
                        .HasColumnType("boolean");

                    b.Property<string>("ListingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("ListingUrlValid")
                        .HasColumnType("boolean");

                    b.Property<bool>("NameMatches")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ObservedRetailerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("SourceUrlValid")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WebsiteUrlValid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("RetailerId", "VerifiedAtUtc");

                    b.ToTable("retailer_identity_verifications", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerProductListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscoveryProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalListingId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PackTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RetailerId", "Status");

                    b.HasIndex("PackTypeId", "RetailerId", "ListingUrl")
                        .IsUnique();

                    b.ToTable("retailer_product_listings", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerProductObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PriceAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("PriceCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("RetailerProductListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("RetailerProductListingId", "ObservedAtUtc");

                    b.ToTable("retailer_product_observations", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("BackpackId", "LocationId")
                        .IsUnique();

                    b.ToTable("saved_locations", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackpackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BackpackId", "ProductId")
                        .IsUnique();

                    b.ToTable("saved_products", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.SizeVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsorbencyBasisMethod")
                        .HasColumnType("text");

                    b.Property<string>("AbsorbencySource")
                        .HasColumnType("text");

                    b.Property<string>("FitMeasurementBasis")
                        .HasColumnType("text");

                    b.Property<int?>("HipMaximumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("HipMinimumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<string>("ManufacturerSize")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ManufacturerStatedAbsorbencyMl")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WaistMaximumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WaistMinimumCm")
                        .HasColumnType("integer");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("integer");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId", "ManufacturerSize")
                        .IsUnique();

                    b.ToTable("size_variants", "diaperscout", t =>
                        {
                            t.HasCheckConstraint("CK_size_variants_waist_range", "\"WaistMinimumCm\" IS NULL OR \"WaistMaximumCm\" IS NULL OR \"WaistMinimumCm\" <= \"WaistMaximumCm\"");
                        });
                });

            modelBuilder.Entity("DiaperScout.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("users", "diaperscout");
                });

            modelBuilder.Entity("DiaperScout.Domain.Backpack", b =>
                {
                    b.HasOne("DiaperScout.Domain.ExplorerProfile", null)
                        .WithOne("Backpack")
                        .HasForeignKey("DiaperScout.Domain.Backpack", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Brand", b =>
                {
                    b.HasOne("DiaperScout.Domain.Manufacturer", null)
                        .WithMany("Brands")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueAuditRecord", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ActingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmission", b =>
                {
                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("PublishedProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionEditorialDecision", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ModeratorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.CatalogueSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionImage", b =>
                {
                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.CatalogueSubmission", null)
                        .WithMany("Images")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionRetailAffiliate", b =>
                {
                    b.HasOne("DiaperScout.Domain.CatalogueSubmissionRetailDestination", null)
                        .WithMany()
                        .HasForeignKey("RetailDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.CatalogueSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_catalogue_submission_retail_affiliates_catalogue_submissio~1");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionRetailDestination", b =>
                {
                    b.HasOne("DiaperScout.Domain.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.CatalogueSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionSizeVariant", b =>
                {
                    b.HasOne("DiaperScout.Domain.CatalogueSubmissionVariant", null)
                        .WithMany("Sizes")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVariant", b =>
                {
                    b.HasOne("DiaperScout.Domain.CatalogueSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVariantOverride", b =>
                {
                    b.HasOne("DiaperScout.Domain.CatalogueSubmissionVariant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVerification", b =>
                {
                    b.HasOne("DiaperScout.Domain.CatalogueSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.DiscoveryTask", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.KnowledgeGap", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeGapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Observation", null)
                        .WithMany()
                        .HasForeignKey("ResultingObservationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.EditorialDecision", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ModeratorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.EvidenceItem", b =>
                {
                    b.HasOne("DiaperScout.Domain.Observation", null)
                        .WithMany("Evidence")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.ExplorerProfile", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithOne("ExplorerProfile")
                        .HasForeignKey("DiaperScout.Domain.ExplorerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.KnowledgeGap", b =>
                {
                    b.HasOne("DiaperScout.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.Location", b =>
                {
                    b.HasOne("DiaperScout.Domain.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Observation", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DiaperScout.Domain.PackType", b =>
                {
                    b.HasOne("DiaperScout.Domain.SizeVariant", null)
                        .WithMany("PackTypes")
                        .HasForeignKey("SizeVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.PrivilegedRoleAssignment", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.PrivilegedRoleAssignmentAudit", b =>
                {
                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ActingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Product", b =>
                {
                    b.HasOne("DiaperScout.Domain.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiaperScout.Domain.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductIdentifier", b =>
                {
                    b.HasOne("DiaperScout.Domain.PackType", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("PackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductVariant", b =>
                {
                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerAffiliateProgramme", b =>
                {
                    b.HasOne("DiaperScout.Domain.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerIdentityVerification", b =>
                {
                    b.HasOne("DiaperScout.Domain.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerProductListing", b =>
                {
                    b.HasOne("DiaperScout.Domain.PackType", null)
                        .WithMany()
                        .HasForeignKey("PackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.RetailerProductObservation", b =>
                {
                    b.HasOne("DiaperScout.Domain.RetailerProductListing", null)
                        .WithMany()
                        .HasForeignKey("RetailerProductListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedLocation", b =>
                {
                    b.HasOne("DiaperScout.Domain.Backpack", null)
                        .WithMany("SavedLocations")
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.SavedProduct", b =>
                {
                    b.HasOne("DiaperScout.Domain.Backpack", null)
                        .WithMany("SavedProducts")
                        .HasForeignKey("BackpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiaperScout.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.SizeVariant", b =>
                {
                    b.HasOne("DiaperScout.Domain.ProductVariant", null)
                        .WithMany("Sizes")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiaperScout.Domain.Backpack", b =>
                {
                    b.Navigation("SavedLocations");

                    b.Navigation("SavedProducts");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmission", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DiaperScout.Domain.CatalogueSubmissionVariant", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("DiaperScout.Domain.ExplorerProfile", b =>
                {
                    b.Navigation("Backpack");
                });

            modelBuilder.Entity("DiaperScout.Domain.Manufacturer", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("DiaperScout.Domain.Observation", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("DiaperScout.Domain.PackType", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("DiaperScout.Domain.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("DiaperScout.Domain.ProductVariant", b =>
                {
                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("DiaperScout.Domain.SizeVariant", b =>
                {
                    b.Navigation("PackTypes");
                });

            modelBuilder.Entity("DiaperScout.Domain.User", b =>
                {
                    b.Navigation("ExplorerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
